version: '3.3'
services:
  wireguard:
    image: linuxserver/wireguard 
    container_name: wireguard
    privileged: true
    cap_add:
      - ALL
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Buenos_Aires
      # next options are optional
      - SERVERURL=1.1.1.1
      - SERVERPORT=51820
      - PEERS=2
      - PEERDNS=auto
      - INTERNAL_SUBNET=10.13.13.0
    volumes:
      - /home/centos/wireguard:/config
      - /usr/src:/usr/src
      #- /usr/src/kernels/4.18.0-348.7.1.el8_5.x86_64:/lib/modules
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
