version: '3.3'
services:
  wireguard:
    image: linuxserver/wireguard 
    container_name: wireguard
    privileged: true
    networks:
      - host
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Buenos_Aires
      # next options are optional
      - SERVERPORT=51820
      - PEERS=6
      - PEERDNS=auto
      - INTERNAL_SUBNET=10.13.13.0
    volumes:
      - /home/centos/wireguard:/config
      - /usr/src:/usr/src
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
